version: 0.0
os: windows
files:
  - source: \
    destination: C:\Simplico
hooks:
  BeforeInstall:
    - location: \Simplico.bat
      timeout: 300
      runas: Administrator
  AfterInstall:
    - location: \Simplico-After
      timeout: 300
      runas: Administrator


